plugins {
    id 'java'
    id 'io.qameta.allure' version '2.12.0'
}

group = 'ru.itmo'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    implementation 'org.seleniumhq.selenium:selenium-java:4.23.0'
    testImplementation 'io.qameta.allure:allure-junit5:2.27.0'
}

test {
    useJUnitPlatform()

    maxParallelForks = 1

    systemProperty "demo", System.getProperty("demo", "false")

    testLogging {
        events "passed", "skipped", "failed"
    }
}

allure {
    version = '2.27.0'
}